# Dump the changelog necessary for F-Droid

name: "F-Droid Changelog"

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  changelog:
    permissions:
      contents: write  # for Git to git push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'master'
      - name: Dump Changelog
        shell: bash
        run: |
          # ${GITHUB_REF_NAME:1} removes the leading "v" letter in tag
          cat CHANGES.md | sed --silent "/\# ${GITHUB_REF_NAME:1}/,/\# /p" | head --lines -2 > default.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Dump changes to default.txt"
          git push origin HEAD:master
